base_cfg: "configs/base.yaml"

tta_dataset:
  name: "graspclutter6d"
  camera: "realsense"  # Camera split [realsense/kinect]
  split: "train"  # Data split [test/test_seen/test_similar/test_novel/test_seen_mini]

eval_dataset:
  name: "graspnet1b"
  camera: "realsense"  # Camera split [realsense/kinect]
  split: "test_similar_mixed"  # Data split [test/test_seen/test_similar/test_novel/test_seen_mini]

# Model settings
graspnet:
  ckpt_path: "ckpts/checkpoint-rs.tar"
  collision_thresh: 0.01  # Collision Threshold in collision detection 
  voxel_size: 0.01  # Voxel Size to process point clouds before collision detection

tta:
  batch_size: 1
  method: "tta-grasp"  # Test Time Adaptation methods [none/ema/cotta/testadagrasp/tent/bn-1/alpha-bn]
  ema_ratio: 0.99  # EMA ratio
  rst_ratio: 0.1  # Restore ratio
  aug_types: "none,hflip"  # Augmentation types for teacher ensemble
  use_student_aug: true
  lr: 1e-4 # Learning rate for TTA
  optimizer: "adamw"
  geval_net:
    model: "dgcnn"
    ckpt_path: "ckpts/gevalnet-dgcnn.tar"
    max_grasp_num: 512
    batch_size: 128
    min_points: 512
    grasp_q_thresh: 0.3 # Grasp score threshold
    geval_score_lamda: 0.0
    nms_on: false
    weighted_loss: false
  contrastive_loss: 
    thresh: 0.3
    temperature: 0.1
    weight: 0.0
    head_dim: 256
  analytical_sampling: 
    use: false
    num_grasp_samples: 1024
    config_file_path: '/home/seung/Workspaces/grasp/TestAdaGrasp/ext/pygpg/gripper_params_g1b.cfg'

