base_cfg: "configs/base.yaml"

tta_dataset:
  name: "graspnet1b"
  camera: "realsense"  # Camera split [realsense/kinect]
  split: "test_similar_mixed_mini"  # Data split [test/test_seen/test_similar/test_novel/test_seen_mini]

eval_dataset:
  name: "graspnet1b"
  camera: "realsense"  # Camera split [realsense/kinect]
  split: "test_similar_mixed_mini"  # Data split [test/test_seen/test_similar/test_novel/test_seen_mini]

# Model settings
model:
  ckpt_path: "ckpts/checkpoint-rs.tar"
  collision_thresh: 0.01  # Collision Threshold in collision detection 
  voxel_size: 0.01  # Voxel Size to process point clouds before collision detection

# Test-time adaptation settings
tta:
  batch_size: 1 
  method: "cotta"  # Test Time Adaptation methods [none/ema/cotta/testadagrasp/tent/bn-1/alpha-bn]
  ema_ratio: 0.995  # EMA ratio
  rst_ratio: 0.1  # Restore ratio
  aug_types: "none,hflip"  # Augmentation types for teacher model
  lr: 1e-4 # Learning rate for TTA
  optimizer: "adamw"
  grasp_score_thresh: 0.0 # Grasp score threshold

# Other settings
seed: 7  # Random seed
mode: "infereval" # Mode [infereval / infer / eval]
num_workers: 4  # Number of workers used in evaluation
