# Base Configuration

# wandb settings
wandb:
  project_name: "TTA-Grasp"
  log_artifact: true
  log_model: false
  entity: "shback"

model:
  name: "graspnet_baseline"
  num_point: 20000  # Point Number
  num_view: 300  # View Number
  voxel_size: 0.01  # Voxel Size to process point clouds before collision detection
  collision_thresh: 0.01  # Collision Threshold in collision detection 


# Dataset settings
graspnet1b:
  root: "/home/seung/Workspaces/Datasets/GraspNet-1Billion"
graspclutter6d:
  root: "/home/seung/Workspaces/Datasets/GraspClutter6D"


seed: 7  # Random seed
mode: "infereval" # Mode [infereval / infer / eval]
num_workers: 4  # Number of workers used in evaluation