base_cfg: "configs/base.yaml"

tta_dataset:
  name: "graspnet1b"
  camera: "realsense"  # Camera split [realsense/kinect]
  split: "test_similar_mixed_mini"  # Data split [test/test_seen/test_similar/test_novel/test_seen_mini]

eval_dataset:
  name: "graspnet1b"
  camera: "realsense"  # Camera split [realsense/kinect]
  split: "test_similar_mixed_mini"  # Data split [test/test_seen/test_similar/test_novel/test_seen_mini]

# Model settings
model:
  ckpt_path: "ckpts/economicgrasp_realsense.tar"

tta:
  batch_size: 1
  window_length: 1
  method: "tent"  # Test Time Adaptation methods [none/ema/cotta/testadagrasp/tent/bn-1/alpha-bn]
  lr: 1e-5 # Learning rate for TTA
  optimizer: "adamw"
  backbone_lr_ratio: 1.0  # Learning rate ratio for backbone
